### PR TITLE
Add passid option for passing the progress meter id to the called fun…

### PR DESCRIPTION
**Pull request by ajdunlap**
…ction

Proposal to solve #3

### CODE REVIEW

**Comment by slundberg** [comment]
Thanks! The failing unit tests on 0.5 are fine, but could you add a simple unit test that passes in 0.4 to make sure this continues to work in the future?

**Comment by ajdunlap** [comment]
I changed the way it works to pass a callback instead of an ID, and also added a test. Sorry for the delay.

**Comment by slundberg** [comment]
Thanks. I does not run for me though, can you check again that it is working? I also am not sure why `updateProgressMeter` is given `n` but it is not used.

**Comment by ajdunlap** [comment]
Very sorry -- forgot to run addprocs() before testing. Now it passes the Travis CI tests on Linux at least.

**Comment by slundberg** [comment]
No problem. I'll wait for the mac tests to run then merge. Thanks!

**Pull request merged**
